<?php

/**
 * @file
 * Contains taxonomy_from_content.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function taxonomy_from_content_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the taxonomy_from_content module.
    case 'help.page.taxonomy_from_content':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Auto tax content with taxonomy terms') . '</p>';
      return $output;

    default:
  }
}
