<?php

/**
 * @file
 * Contains taxonomy_from_content.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function taxonomy_from_content_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the taxonomy_from_content module.
    case 'help.page.c':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Tags content with taxonomy terms that exist in a taxonomy library') . '</p>';
      return $output;

    default:
  }

function taxonomy_from_content_entity_presave(Drupal\Core\Entity\EntityInterface $entity){
	
}