<?php

/**
 * @file
 * Contains a_bdynamic_copyright_block.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function a_bdynamic_copyright_block_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the a_bdynamic_copyright_block module.
    case 'help.page.a_bdynamic_copyright_block':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Provides copyright block') . '</p>';
      return $output;

    default:
  }
}
