<?php

/**
 * @file
 * Contains dynamic_copyright_block.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function dynamic_copyright_block_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the dynamic_copyright_block module.
    case 'help.page.dynamic_copyright_block':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Provides a copyright block which displays the current year.') . '</p>';
      return $output;

    default:
  }
}
